import { BORDERS, type Border } from "./shader/embroidery";

const LIGHT = { bg: "#f4f1e8", red: "#b4232a", ink: "#1a1a1a" };
const DARK = { bg: "#191c16", red: "#d8aa54", ink: "#e9e5d8" };
const CELL = 8; // px per stitch in the intrinsic SVG (background-size scales it)

// One tileable band as an SVG data-URI: a background rect (linen/paper) plus one
// <rect> per non-empty stitch. encodeURIComponent keeps it valid inside CSS url().
export function bandSVG(b: Border, light: boolean): string {
  const p = light ? LIGHT : DARK;
  const W = b.cols * CELL, H = b.rows * CELL;
  let rects = "";
  for (let r = 0; r < b.rows; r++) {
    const row = b.cells[r];
    for (let c = 0; c < b.cols; c++) {
      const ch = row[c];
      if (ch === ".") continue; // linen = background
      const fill = ch === "R" ? p.red : p.ink;
      rects += `<rect x='${c * CELL}' y='${r * CELL}' width='${CELL}' height='${CELL}' fill='${fill}'/>`;
    }
  }
  const svg = `<svg xmlns='http://www.w3.org/2000/svg' width='${W}' height='${H}' shape-rendering='crispEdges'><rect width='${W}' height='${H}' fill='${p.bg}'/>${rects}</svg>`;
  return `data:image/svg+xml,${encodeURIComponent(svg)}`;
}

const TOKENS: Record<"a" | "b" | "c", string> = {
  a: "upa_2c1afca8547010f7",
  b: "upa_a83394df6ae60276",
  c: "upa_6cdef2752bd9b5fb",
};

function byId(id: string): Border {
  const b = BORDERS.find((x) => x.id === id);
  if (!b) throw new Error(`embroidery token not found: ${id}`);
  return b;
}

// Full generated stylesheet: --emb-a/b/c on :root (light), overridden for dark
// (manual [data-theme="dark"] and auto prefers-color-scheme, mirroring styles.css).
export function embroideryCss(): string {
  const block = (light: boolean) =>
    (Object.keys(TOKENS) as Array<keyof typeof TOKENS>)
      .map((k) => `  --emb-${k}: url("${bandSVG(byId(TOKENS[k]), light)}");`)
      .join("\n");
  const dark = block(false);
  return `/* GENERATED by build_embroidery (see src/embroidery-css.ts) — do not edit. */
:root {
${block(true)}
}
:root[data-theme="dark"] {
${dark}
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${dark}
  }
}
`;
}
